name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install --quiet -y libglfw3 libglfw3-dev libfreetype6-dev libgtk-3-dev
    - name: Build V
      run: |
        git clone --depth 1 https://github.com/vlang/v ../v
        cd ../v
        make
    - name: cp ui => vlib/ui, without installing
      run: cp -rf ../ui ../v/vlib/ui
    - name: Build UI examples
      run: |
        for f in examples/*.v; do echo "Building $f ..."; ../v/v $f ; done
    - name: Results
      run: |
        ls -lart examples/* | grep -v .v$

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        brew install freetype glfw
    - name: Build V
      run: |
        git clone --depth 1 https://github.com/vlang/v ../v
        cd ../v
        make
    - name: cp ui => vlib/ui, without installing
      run: cp -rf ../ui ../v/vlib/ui
    - name: Build UI examples
      run: |        
        for f in examples/*.v; do echo "Building $f ..."; ../v/v $f ; done
    - name: Results
      run: |        
        ls -lart examples/* | grep -v .v$

  windows-msvc:
    runs-on: windows-latest
    env:
        VFLAGS: -cc msvc
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        echo %VFLAGS%
        git clone --depth 1 https://github.com/vlang/v ..\v
        git clone --depth=1 https://github.com/ubawurinna/freetype-windows-binaries.git ..\v\thirdparty\freetype
    - name: Build V
      run: |
        cd ..\v
        .\make.bat -msvc
    - name: cp ui => vlib/ui, without installing
      run: |
        xcopy ..\ui ..\v\vlib\ui /e /i /h
    - name: Build UI demo
      run: |
        ..\v\v.exe examples\group.v
        ..\v\v.exe examples\users.v
        ..\v\v.exe examples\calculator.v
    - name: Results
      run: |
        dir examples\
