name: CI

on: [push, pull_request]

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install --quiet -y libglfw3 libglfw3-dev libfreetype6-dev libgtk-3-dev
    - name: Build examples
      run: |
        cd ..
        git clone --depth 1 https://github.com/vlang/v
        cd v && make
        cd ..
        cp -rf ui v/vlib/ui
        cd ui
        ../v/v examples/users/users.v

  macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        brew install freetype glfw
    - name: Build examples
      run: |
        cd ..
        git clone --depth 1 https://github.com/vlang/v
        cd v && make
        cd ..
        cp -rf ui v/vlib/ui
        cd ui
        ../v/v examples/users/users.v
